### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by ZhiliWang** [thunlp/jec-qa#1]
Hi. I requested multiple times on your site (http://jecqa.thunlp.org/) for the dataset, stated that it would strictly for research purposes, but never got a reply. Is there any other way to access the actual QA dataset? Thank you.

**Comment by haoxizhong** [comment]
You must use your school email, not other mail address like gmail. Only then we can make sure that you use it for research. If you don't have a school email, please post the reason.

**Comment by ZhiliWang** [comment]
I have received it, thank you so much!

**Comment by kchanLuo** [comment]
> 我已经收到了，非常感谢！

Hello, do you have data-set backup? I wanted to download it but now the official link is broken.
