### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Decalogue** [thunlp/jec-qa#2]
您好!
我在您的代码上跑法研杯的数据时发现没有 reference 这一项,请问您的数据格式和法研杯数据的格式不一样吗?另外在转换 label 后的 k = [0, 1, 2, 6, 12, 7, 13, 3, 8, 9, 14, 15, 4, 10, 16, 5, 16, 17] 这个您能注释一下吗?我看到里面有2个16是重复的,如果对应选 topk 的话这些是不是对应某种选项组合关系?
多谢了!

**Comment by haoxizhong** [comment]
这个不是法研杯项目，你得到隔壁去看法研杯的baseline。

**Comment by Decalogue** [comment]
多谢了!之前法研杯贴出的数据来源就是这篇论文.当时官方没有上传 baseline, 刚才才看到官方上传.

**Comment by haoxizhong** [comment]
但法研杯数据也提供了自己的baseline啊

**Comment by haoxizhong** [comment]
你说的这个reference数据是这篇文章的考纲 这个数据不在法研杯那边

**Comment by Decalogue** [comment]
感谢!
